### PR TITLE
fixed limit expression parse bug

### PR DESCRIPTION
**Pull request by brennanjl**
Working branch for working through other parse bugs.

Currently solves:
- https://github.com/kwilteam/kwil-db/issues/809

### CODE REVIEW

**Comment by jchappelow** [comment]
Will you please sneak this change in?

```diff
diff --git a/internal/voting/voting.go b/internal/voting/voting.go
index 508676c9..df4e0837 100644
--- a/internal/voting/voting.go
+++ b/internal/voting/voting.go
@@ -49,7 +49,7 @@ func initializeVoteStore(ctx context.Context, db sql.TxMaker) error {
        resolutions := resolutions.ListResolutions()
        for _, name := range resolutions {
                uuid := types.NewUUIDV5([]byte(name))
-               fmt.Println("Creating resolution type", name, " with UUID: ", uuid, " value: ", *uuid, " uuid[:] ", uuid[:])
+               fmt.Printf("Creating resolution type %q with UUID %v\n", name, uuid)
                _, err := tx.Execute(ctx, createResolutionType, uuid[:], name)
                if err != nil {
                        return err
```

There's no logger here, nbd, but the actual printout there is messed up.

**Review by jchappelow — APPROVED** [review]
LGTM.  @Yaiba can you take a quick scan at the antlr.go change?

**Comment by Yaiba** [comment]
> LGTM. @Yaiba can you take a quick scan at the antlr.go change?

sure

**Review by Yaiba — APPROVED** [review]
LGTM

**Comment by jchappelow** [comment]
@Yaiba sorry, I pushed a minor change to and error return's details: https://github.com/kwilteam/kwil-db/pull/810/commits/b7e32e065bdd2c4e64e15386979078cfa2815195
Will you please reapprove :pray:

**Review by Yaiba — APPROVED** [review]

**Pull request merged**
