### PR TITLE
ci: fix kgw test workflow

### PR DESCRIPTION
**Pull request by Yaiba**
This will fix the kgw test on main for kwil-js, it's failing https://github.com/kwilteam/kwil-db/actions/runs/9102720328/job/25022987925.

~~This run https://github.com/kwilteam/kwil-db/actions/runs/9102996054 (against kwild `main` branch) should success before we merge this PR. And for this PR I pushed a branch to this repo, will delete afterward.~~ This rerun won't work.

### CODE REVIEW

**Comment by Yaiba** [comment]
This run https://github.com/kwilteam/kwil-db/actions/runs/9116100989 is against current `ci/fix-kgw-test` branch, if we make changes to kwild logic, we should re-run this and see the result

**Comment by Yaiba** [comment]
> This run https://github.com/kwilteam/kwil-db/actions/runs/9116100989 is against current `ci/fix-kgw-test` branch, if we make changes to kwild logic, we should re-run this and see the result @charithabandi

https://docs.github.com/en/actions/managing-workflow-runs/re-running-workflows-and-jobs#about-re-running-workflows-and-jobs.  

> Re-running a workflow or jobs in a workflow uses the same GITHUB_SHA (commit SHA) and GITHUB_REF (Git ref) of the original event that triggered the workflow run

That's why it didn't work as expected.

**Comment by Yaiba** [comment]
https://github.com/kwilteam/kwil-db/actions/runs/9161574685/job/25186730490   This run uses workflow from current branch, and also test against current branch, all tests passed, should be good to go

**Review by jchappelow — APPROVED** [review]
LGTM.   Sorry I missed this.

**Pull request merged**
