### PR TITLE
[v0.7.5]  update gomod for core module version bump

### PR DESCRIPTION
**Pull request by Yaiba**
This pr is going to update go.mod which deps on core/v0.1.3(to tag, I'll tag it once I'm sure no more changes will be made to core module).

### CODE REVIEW

**Comment by jchappelow** [comment]
Might need to alter this to v0.7.5 :hand_over_mouth:

**Comment by brennanjl** [comment]
Whoops my bad I should've included this

**Comment by Yaiba** [comment]
my bad as well, I lost track of what's going on yesterday. This will go into v0.7.5

**Comment by jchappelow** [comment]
OK to update.  Nothing else for v0.7.5 I think.

**Comment by Yaiba** [comment]
> OK to update. Nothing else for v0.7.5 I think.

we need #691 backported

**Comment by jchappelow** [comment]
> > OK to update. Nothing else for v0.7.5 I think.
> 
> we need #691 backported

Reviewing now.

**Comment by jchappelow** [comment]
I think I can tag `core/v0.1.3` now, on `release-v0.7` branch.  https://github.com/kwilteam/kwil-db/pull/715 does not touch `core` code.  Sound ok @Yaiba ?  

a325df6865074c11282c211b472ef3f8887a09ba looks appropriate, although I think last change to core was 4863d6936275625215b9bfa8120872a5cd1685d4

**Comment by Yaiba** [comment]
> I think I can tag `core/v0.1.3` now, on `release-v0.7` branch. #715 does not touch `core` code. Sound ok @Yaiba ?
> 
> [a325df6](https://github.com/kwilteam/kwil-db/commit/a325df6865074c11282c211b472ef3f8887a09ba) looks appropriate, although I think last change to core was [4863d69](https://github.com/kwilteam/kwil-db/commit/4863d6936275625215b9bfa8120872a5cd1685d4)

yeah good to go

**Comment by jchappelow** [comment]
tag: https://github.com/kwilteam/kwil-db/releases/tag/core%2Fv0.1.3

**Review by jchappelow — APPROVED** [review]

**Comment by jchappelow** [comment]
Dang, I can't merge because I had last commit

**Comment by Yaiba** [comment]
> Dang, I can't merge because I had last commit

lol

**Review by KwilLuke — APPROVED** [review]
LGTM 😂

**Pull request merged**
