### PR TITLE
change kwil-cli config and flags 

### PR DESCRIPTION
**Pull request by Yaiba**
BREAKING CHANGE:
- change flags `kwil-provider` to `provider`
- change config field `grpc_url` to `provider`
- change default config folder from `~/.kwil_cli` to `~/.kwil-cli`

### CODE REVIEW

**Review by jchappelow — APPROVED** [review]
LGTM.  If the folder name is changing, I think we can just make this provider setting switch without deprecating or detecting an old grpc_url setting.

**Comment by Yaiba** [comment]
> LGTM. If the folder name is changing, I think we can just make this provider setting switch without deprecating or detecting an old grpc_url setting.

you mean like this ?
```
type kwilCliPersistedConfig struct {
        ...
	// Deprecated: use `Provider` instead
	GrpcURL  string `mapstructure:"grpc_url" json:"grpc_url,omitempty"`
	Provider string `mapstructure:"provider" json:"provider,omitempty"`
        ...
}
```

**Comment by jchappelow** [comment]
> you mean like this ?

Right.  I had done just that in #679.  That also required a bunch of code to support backward compat, so I decided there's little point looking for the old field, particularly because it's already looking in a different folder (`.kwil-cli` instead of `.kwil_cli`)

**Comment by Yaiba** [comment]
> > you mean like this ?
> 
> Right. I had done just that in #679. That also required a bunch of code to support backward compat, so I decided there's little point looking for the old field, particularly because it's already looking in a different folder (`.kwil-cli` instead of `.kwil_cli`)

Alright cool. 
 @brennanjl do you have concerns on this breaking changes?

**Comment by brennanjl** [comment]
Yeah this seems fine to me. I don't think many people rely on the persisted config anyways. Fractal seems to pass everything with flags, and Truflation has built their own Go server for writing to Kwil.

**Review by brennanjl — APPROVED** [review]

**Pull request merged**
