### PR TITLE
[v0.8.2] added look back for token errors

### PR DESCRIPTION
**Pull request by brennanjl**
Backport https://github.com/kwilteam/kwil-db/pull/838 to release-v0.8

### CODE REVIEW

**Comment by KwilLuke** [comment]
Should this be added to DB admin? @brennanjl

**Comment by brennanjl** [comment]
> Should this be added to DB admin? @brennanjl

Yes

**Review by jchappelow — APPROVED** [review]
OK.  @Yaiba ?

**Comment by Yaiba** [comment]
> OK. @Yaiba ?

yeah, sorry didn't catch this pr

**Review by Yaiba — APPROVED** [review]

**Comment by jchappelow** [comment]
Does `kwild` need this change?  i.e. need an update to `kwil-db` main module to build apps with this change?  Or is this just for other consumers of the parser?

**Pull request merged**
