### PR TITLE
simplify expressions in the planner

### PR DESCRIPTION
**Pull request by brennanjl**
This PR simplifies comparisons in logical plans by limiting the number of operators. I felt this change was good b/c of how I am managing them within procedures.

### CODE REVIEW

**Review by Yaiba — APPROVED** [review]
LGTM.  
There are not test cases so cannot verify the changes

**Comment by brennanjl** [comment]
These are covered by existing planner tests.

**Comment by Yaiba** [comment]
> These are covered by existing planner tests.

Do you mean the existing tests 'results' are already using the simplifed expressions?  I don't see tests with `!=` `>=` `<=`

**Comment by Yaiba** [comment]
oh, the planner tests cannot tell the difference

> > These are covered by existing planner tests.
> 
> Do you mean the existing tests 'results' are already using the simplifed expressions? I don't see tests with `!=` `>=` `<=`

oh, wait, the planner tests cannot tell the difference :/

**Pull request merged**
