### PR TITLE
check for invalid delimiter

### PR DESCRIPTION
**Pull request by brennanjl**
This adds a delimiter `$kwil_reserved_delim$`, and checks that users aren't trying to maliciously use it in procedure or table creation.

We should not backport this to the TSN fix, since it is a breaking change with how snapshots are created.

### CODE REVIEW

**Comment by brennanjl** [comment]
One pretty big issue we might have here is upgradability.

Any old schema will be pgdumped with the `$$` delimiter. I guess its not too big a deal since it won't break anything, but its something we should keep in mind.

**Review by jchappelow — APPROVED** [review]
LGTM

**Comment by jchappelow** [comment]
> Any old schema will be pgdumped with the `$$` delimiter. I guess its not too big a deal since it won't break anything, but its something we should keep in mind.

Mmmm, no ideal but I also imagine that's fine, particularly given there has been no real working snapshots yet anyway.

Still, just throwing this out there -- dump sanitize could do a string replacement, but we risk messing up the dump if not done just so.

**Comment by brennanjl** [comment]
> Mmmm, not ideal but I also imagine that's fine, particularly given there has been no real working snapshots yet anyway.

Still, just throwing this out there -- dump sanitize could do a string replacement, but we risk messing up the dump if not done just so.

The thing is, we only want to replace the string for dumps that are using the current `$$` delimiter, instead of `$kwil_reserved_delim$`. IMO it seems more error prone, especially since dumps using the current delimiter would work find anyways.

**Pull request merged**
