### PR TITLE
[v0.6.7] bundle backport

### PR DESCRIPTION
**Pull request by Yaiba**
This backports:
- #507 
- #624 
- #645
- #647

### CODE REVIEW

**Comment by jchappelow** [comment]
Would you also update internal/version/version.go so it reports 0.6.7? and not a beta?

**Comment by Yaiba** [comment]
> Would you also update internal/version/version.go so it reports 0.6.7? and not a beta?

sure

**Comment by jchappelow** [comment]
Want to include https://github.com/kwilteam/kwil-db/pull/646/commits/4b98b271edf16ffb9030e7a86216daec17ef4a86 in this PR or make a separate 0.6.7 backport PR for that?  I'm not particular about bundling backports vs. multiple discrete backport PRs as long as the PR is closed via rebase rather than squash.

**Comment by Yaiba** [comment]
> Want to include [4b98b27](https://github.com/kwilteam/kwil-db/commit/4b98b271edf16ffb9030e7a86216daec17ef4a86) in this PR or make a separate 0.6.7 backport PR for that? I'm not particular about bundling backports vs. multiple discrete backport PRs as long as the PR is closed via rebase rather than squash.

Yes, I'll bundle them in this pr

**Review by jchappelow — APPROVED** [review]

**Pull request merged**
